### PR TITLE
Fix for nav in pageheader

### PR DESCRIPTION
**Pull request by kits4**
### What does this implement/fix? Explain your changes.
Fixes horizontal navigation in Pageheader component
...

### Does this close any currently open issues?
Yes, solves #920 
...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

### CODE REVIEW

**Review by satyamyadav — CHANGES_REQUESTED** [review]
@kits4 Please update the following points for your PR:

- There should not be any merge commit and there should be only one commit, to avoid merge commits on taking pull from upstream use `--rebase` flag , like `git pull --rebase upstream develop`.
- Commit message should follow [our guideline](https://github.com/innovaccer/design-system/blob/master/CONTRIBUTING.md#commit-guidelines), you can use `commitizen/cz-cli` for which we have commit hook configured in this repo also.

**Comment by kits4** [comment]
should i make a new pr
as on rebasing this happened

**Comment by kits4** [comment]
The required changes are made in PR #937  
you can close this pr and review the other one.

Thank You!!

**Comment by satyamyadav** [comment]
@kits4 Closing this PR in favour of #937 .

**Pull request closed without merging**
