### PR TITLE
Fixed Typo in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Sumit2399**
### What does this implement/fix? Explain your changes.
Fixed typo In CONTRIBUTING.md

...

### Does this close any currently open issues?
#430 

...

### Any other comments?
Hoping for merge soon.
...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch

### CODE REVIEW

**Comment by Sumit2399** [comment]
Check this out, @g3kgirl @satyamyadav.

**Review by riyalohia — APPROVED** [review]

**Comment by Sumit2399** [comment]
Hi @riyalohia,could you please explain why there is an error of Merging is blocked?
How can I fix it as it did not resolve even after your approval?

**Review by sandeshchoudhary — COMMENTED** [review]
Please raise this PR to develop branch. Also, follow proper naming convention for branch name.

**Comment by sandeshchoudhary** [comment]
Already merged for develop branch.

**Pull request closed without merging**
