### PR TITLE
fix(Grid): fixes Pin Right #97

### PR DESCRIPTION
**Pull request by aditya-kumawat**
### What does this implement/fix? Explain your changes.
- Fixes Pin Right.
- Removes reorderCol and reorderHighlighter from Grid.
- Updates column order in DynamicColumn Dropdown in Header.
...

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

### CODE REVIEW

**Review by satyamyadav — CHANGES_REQUESTED** [review]
@aditya-kumawat  Currently when we pin a column to right or left the column's position (column name) in `dynamicColumn ` dropdown is not affected, is this an expected behaviour ?

Also regarding  commit message formatting, you can use format like `git commit -m "feat(SCOPE): Title of commit message." -m "Description of commit message" -m "Footer of commit message."` to get commit message like : 
```shell
    feat(SCOPE): Title of commit message.

    Description of commit message

    Footer of commit message.
```
Please follow [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by aditya-kumawat** [comment]
> @aditya-kumawat Currently when we pin a column to right or left the column's position (column name) in `dynamicColumn ` dropdown is not affected, is this an expected behaviour ?
> 
> Also regarding commit message formatting, you can use format like `git commit -m "feat(SCOPE): Title of commit message." -m "Description of commit message" -m "Footer of commit message."` to get commit message like :
> 
> ```shell
>     feat(SCOPE): Title of commit message.
> 
>     Description of commit message
> 
>     Footer of commit message.
> ```
> 
> Please follow [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

@satyamyadav I didn't update Dynamic Column Dropdown in case of pinned. Do we need to update it?
Sure, will follow the commit naming conventions.

**Comment by satyamyadav** [comment]
> I didn't update Dynamic Column Dropdown in case of pinned. 
Yes, the order in dropdown should update as it happens in case of column reordering, same should be the flow for pin/unpin actions as it affects the order of columns also.

**Comment by aditya-kumawat** [comment]
> > I didn't update Dynamic Column Dropdown in case of pinned.
> > Yes, the order in dropdown should update as it happens in case of column reordering, same should be the flow for pin/unpin actions as it affects the order of columns also.

I already updated this in the same PR.

**Review by satyamyadav — APPROVED** [review]

**Pull request merged**
